packages:
  - "cell"
  - "cell/packages/*"
  - "shared"
  - "shared/packages/*"
  - "backend"
  - "backend/packages/*"
  - "desktop"
  - "frontend/packages/*"
  - "terminal"
  - "terminal/packages/*"
