export const WORKFLOW_PUBLIC_GATEWAY_TOOL_NAMES = [
  "WorkflowFulfill",
  "WorkflowAuthor",
] as const

export const WORKFLOW_LIFECYCLE_DEFINITION_TOOL_NAMES = [
  "WorkflowLoadStageContext",
  "WorkflowListApps",
  "WorkflowGetApp",
  "WorkflowGetAuthoringContext",
  "WorkflowListAuthoringTemplates",
  "WorkflowListPrebuiltWorkflows",
  "WorkflowListReusableAgents",
  "WorkflowOpenAuthoringSession",
  "WorkflowCreateResourcePackageSession",
  "WorkflowValidateAuthoringSession",
  "WorkflowDryRunAuthoringSession",
  "WorkflowPreparePublication",
  "WorkflowCompleteAuthoring",
  "WorkflowPublishAuthoringSession",
  "WorkflowListAuthoringSessions",
  "WorkflowGetAuthoringSummary",
  "WorkflowWorkspace",
  "WorkflowInspectCapability",
  "WorkflowValidateResourceRef",
  "WorkflowCreateBundle",
  "WorkflowPatchBundle",
  "WorkflowListTypes",
  "WorkflowGetType",
  "WorkflowCreateInstance",
  "WorkflowCreateInstanceFromPrebuilt",
  "WorkflowListInstances",
  "WorkflowListSessionFlows",
  "WorkflowGetInstance",
  "WorkflowUpdateRunVars",
  "WorkflowGetFlowSummary",
  "WorkflowMaterialImport",
  "WorkflowMaterialInspect",
  "WorkflowMaterialBind",
  "WorkflowMaterialExport",
  "WorkflowMaterialReplay",
  "WorkflowMaterialCleanup",
  "WorkflowRun",
  "WorkflowStatus",
  "WorkflowEvents",
  "WorkflowResult",
  "WorkflowResume",
  "WorkflowResolve",
  "WorkflowReject",
  "WorkflowApplyGraphPatch",
  "WorkflowMutateStepExtension",
  "WorkflowProcessHolonTask",
  "WorkflowReplanHolonTask",
] as const

export const WORKFLOW_NATIVE_TOOL_NAMES = [
  ...WORKFLOW_PUBLIC_GATEWAY_TOOL_NAMES,
  ...WORKFLOW_LIFECYCLE_DEFINITION_TOOL_NAMES,
] as const
