import type { ToolDef } from "@cell/ai-core-contract/types"
import {
  runByFuncStyleAdapter,
  stdMakeIdentityInnerConfig,
  stdMakeIdentityInnerInput,
  stdMakeIdentityInnerRuntime,
  stdMakeIdentityOuterOutput,
  stdMakeNullOuterComputed,
} from "depa-processor"
import { workflowCreateBundleCoreLogic } from "./Logic"
import briefPromptXnl from "./Tool.brief.xnl" with { type: "text" }
import detailPromptXnl from "./Tool.detail.xnl" with { type: "text" }
import type {
  WorkflowCreateBundleOuterConfig,
  WorkflowCreateBundleOuterInput,
  WorkflowCreateBundleOuterOutput,
} from "./OuterTypes"

export function buildWorkflowCreateBundleToolDef(): ToolDef<
  WorkflowCreateBundleOuterInput,
  WorkflowCreateBundleOuterOutput,
  WorkflowCreateBundleOuterConfig
> {
  return {
    schema: {
      type: "function",
      function: {
        name: "WorkflowCreateBundle",
        description: "Create a workflow draft or open a recoverable authoring session; this tool never publishes or executes.",
        parameters: {
          type: "object",
          properties: {
            form: {
              type: "string",
              enum: ["AICtrlWorkflow", "AIDataWorkflow", "ai-ctrl", "ai-data"],
              description: "Workflow form to create.",
            },
            name: {
              type: "string",
              description: "Human-readable workflow bundle name.",
            },
            fqn: {
              type: "string",
              description: "Optional resource FQN. Defaults to local.workflow.<PascalName>.",
            },
            description: {
              type: "string",
              description: "Optional workflow description retained in the bundle metadata module.",
            },
            manifest_content: {
              type: "string",
              description: "Optional complete canonical profile manifest generated by the authoring actor.",
            },
            flow_code_content: {
              type: "string",
              description: "Optional complete flow-code/index.ts paired atomically with manifest_content; all manifest code refs must target this file.",
            },
            session_id: {
              type: "string",
              description: "Optional recoverable authoring session id.",
            },
            dry_run: {
              type: "boolean",
              description: "Return a pure canonically validated draft instead of opening an authoring session.",
            },
          },
          required: ["form", "name"],
          additionalProperties: false,
        },
      },
    },
    briefPromptXnl,
    detailPromptXnl,
    run: async (runtime, input, config) =>
      await runByFuncStyleAdapter(
        runtime,
        input,
        config,
        stdMakeNullOuterComputed,
        stdMakeIdentityInnerRuntime,
        stdMakeIdentityInnerInput,
        stdMakeIdentityInnerConfig,
        workflowCreateBundleCoreLogic,
        stdMakeIdentityOuterOutput,
      ),
  }
}
