import type { KeybindsConfig } from "@terminal/core/AIAgent"

export type ShortcutCategory =
  | "System"
  | "Session"
  | "History"
  | "Composer"
  | "Models"
  | "File Picker"
  | "Terminal"

export type ShortcutEntry = {
  id: string
  category: ShortcutCategory
  label: string
  detail: string
  keybind?: keyof KeybindsConfig
  combos?: string[]
}

export const shortcutCatalog: ShortcutEntry[] = [
  {
    id: "command-list",
    category: "System",
    keybind: "command_list",
    label: "Command palette",
    detail: "open all available actions",
  },
  {
    id: "shortcut-overview",
    category: "System",
    keybind: "shortcuts_view",
    label: "Shortcut overview",
    detail: "open this categorized shortcut panel",
  },
  {
    id: "status-view",
    category: "System",
    keybind: "status_view",
    label: "Status",
    detail: "inspect runtime and surface state",
  },
  {
    id: "session-list",
    category: "System",
    keybind: "session_list",
    label: "Sessions",
    detail: "switch or manage saved sessions",
  },
  {
    id: "model-list",
    category: "System",
    keybind: "model_list",
    label: "Models",
    detail: "switch the active model",
  },
  {
    id: "agent-list",
    category: "System",
    keybind: "agent_list",
    label: "Agents",
    detail: "switch the active agent persona",
  },
  {
    id: "theme-list",
    category: "System",
    keybind: "theme_list",
    label: "Appearance",
    detail: "open the theme switcher",
  },
  {
    id: "editor-open",
    category: "System",
    keybind: "editor_open",
    label: "External editor",
    detail: "open the prompt in an editor",
  },
  {
    id: "tips-toggle",
    category: "System",
    keybind: "tips_toggle",
    label: "Tips",
    detail: "toggle inline tips visibility",
  },
  {
    id: "app-exit",
    category: "System",
    keybind: "app_exit",
    label: "Exit app",
    detail: "close the current TUI session",
  },
  {
    id: "session-new",
    category: "Session",
    keybind: "session_new",
    label: "New session",
    detail: "start a fresh session",
  },
  {
    id: "session-export",
    category: "Session",
    keybind: "session_export",
    label: "Export transcript",
    detail: "save the current transcript",
  },
  {
    id: "session-timeline",
    category: "Session",
    keybind: "session_timeline",
    label: "Session timeline",
    detail: "jump through session history",
  },
  {
    id: "session-compact",
    category: "Session",
    keybind: "session_compact",
    label: "Compact session",
    detail: "compress the current conversation",
  },
  {
    id: "session-interrupt",
    category: "Session",
    keybind: "session_interrupt",
    label: "Interrupt turn",
    detail: "stop the active response",
  },
  {
    id: "session-parent",
    category: "Session",
    keybind: "session_parent",
    label: "Parent session",
    detail: "jump to the parent branch",
  },
  {
    id: "session-child-next",
    category: "Session",
    keybind: "session_child_cycle",
    label: "Next child session",
    detail: "cycle forward through child branches",
  },
  {
    id: "session-child-prev",
    category: "Session",
    keybind: "session_child_cycle_reverse",
    label: "Previous child session",
    detail: "cycle backward through child branches",
  },
  {
    id: "history-page-up",
    category: "History",
    keybind: "messages_page_up",
    label: "Page up",
    detail: "scroll history up by one page",
  },
  {
    id: "history-page-down",
    category: "History",
    keybind: "messages_page_down",
    label: "Page down",
    detail: "scroll history down by one page",
  },
  {
    id: "history-half-page-up",
    category: "History",
    keybind: "messages_half_page_up",
    label: "Half page up",
    detail: "scroll history up faster",
  },
  {
    id: "history-half-page-down",
    category: "History",
    keybind: "messages_half_page_down",
    label: "Half page down",
    detail: "scroll history down faster",
  },
  {
    id: "history-first",
    category: "History",
    keybind: "messages_first",
    label: "First message",
    detail: "jump to the oldest visible message",
  },
  {
    id: "history-last",
    category: "History",
    keybind: "messages_last",
    label: "Latest message",
    detail: "jump to the newest visible message",
  },
  {
    id: "history-copy",
    category: "History",
    keybind: "messages_copy",
    label: "Copy transcript",
    detail: "copy the current transcript",
  },
  {
    id: "history-undo",
    category: "History",
    keybind: "messages_undo",
    label: "Undo message",
    detail: "undo the latest message action",
  },
  {
    id: "history-redo",
    category: "History",
    keybind: "messages_redo",
    label: "Redo message",
    detail: "redo the latest undone action",
  },
  {
    id: "history-conceal",
    category: "History",
    keybind: "messages_toggle_conceal",
    label: "Toggle conceal",
    detail: "toggle hidden content rendering",
  },
  {
    id: "composer-submit",
    category: "Composer",
    keybind: "input_submit",
    label: "Submit prompt",
    detail: "send the current prompt",
  },
  {
    id: "composer-newline",
    category: "Composer",
    keybind: "input_newline",
    label: "Insert newline",
    detail: "insert a line break without sending",
  },
  {
    id: "composer-clear",
    category: "Composer",
    keybind: "input_clear",
    label: "Clear input",
    detail: "empty the current draft",
  },
  {
    id: "composer-paste",
    category: "Composer",
    keybind: "input_paste",
    label: "Paste clipboard",
    detail: "paste text or image from the clipboard",
  },
  {
    id: "composer-agent-picker",
    category: "Composer",
    combos: ["ctrl+g"],
    label: "Insert mention",
    detail: "open the agent mention picker",
  },
  {
    id: "composer-file-picker",
    category: "Composer",
    combos: ["ctrl+o"],
    label: "Insert file part",
    detail: "open the workspace file picker",
  },
  {
    id: "composer-history-prev",
    category: "Composer",
    combos: ["alt+up"],
    label: "Previous draft",
    detail: "load the previous prompt from local history",
  },
  {
    id: "composer-history-next",
    category: "Composer",
    combos: ["alt+down"],
    label: "Next draft",
    detail: "load the next prompt from local history",
  },
  {
    id: "composer-line-home",
    category: "Composer",
    keybind: "input_line_home",
    label: "Line start",
    detail: "move the cursor to the start of the line",
  },
  {
    id: "composer-line-end",
    category: "Composer",
    keybind: "input_line_end",
    label: "Line end",
    detail: "move the cursor to the end of the line",
  },
  {
    id: "composer-word-backward",
    category: "Composer",
    keybind: "input_word_backward",
    label: "Word backward",
    detail: "move left by one word",
  },
  {
    id: "composer-word-forward",
    category: "Composer",
    keybind: "input_word_forward",
    label: "Word forward",
    detail: "move right by one word",
  },
  {
    id: "composer-delete-line",
    category: "Composer",
    keybind: "input_delete_line",
    label: "Delete line",
    detail: "remove the current line",
  },
  {
    id: "composer-delete-line-start",
    category: "Composer",
    keybind: "input_delete_to_line_start",
    label: "Delete to line start",
    detail: "delete back to the line start",
  },
  {
    id: "composer-delete-line-end",
    category: "Composer",
    keybind: "input_delete_to_line_end",
    label: "Delete to line end",
    detail: "delete forward to the line end",
  },
  {
    id: "composer-delete-word-backward",
    category: "Composer",
    keybind: "input_delete_word_backward",
    label: "Delete word backward",
    detail: "delete the previous word",
  },
  {
    id: "composer-delete-word-forward",
    category: "Composer",
    keybind: "input_delete_word_forward",
    label: "Delete word forward",
    detail: "delete the next word",
  },
  {
    id: "composer-undo",
    category: "Composer",
    keybind: "input_undo",
    label: "Undo edit",
    detail: "undo the latest draft edit",
  },
  {
    id: "composer-redo",
    category: "Composer",
    keybind: "input_redo",
    label: "Redo edit",
    detail: "redo the latest undone draft edit",
  },
  {
    id: "model-cycle-recent",
    category: "Models",
    keybind: "model_cycle_recent",
    label: "Cycle recent model",
    detail: "move to the next recent model",
  },
  {
    id: "model-cycle-recent-reverse",
    category: "Models",
    keybind: "model_cycle_recent_reverse",
    label: "Cycle recent model reverse",
    detail: "move to the previous recent model",
  },
  {
    id: "variant-cycle",
    category: "Models",
    keybind: "variant_cycle",
    label: "Cycle variant",
    detail: "switch the active model variant",
  },
  {
    id: "agent-cycle",
    category: "Models",
    keybind: "agent_cycle",
    label: "Cycle agent",
    detail: "move to the next agent",
  },
  {
    id: "agent-cycle-reverse",
    category: "Models",
    keybind: "agent_cycle_reverse",
    label: "Cycle agent reverse",
    detail: "move to the previous agent",
  },
  {
    id: "picker-clear-filter",
    category: "File Picker",
    combos: ["ctrl+l"],
    label: "Clear filter",
    detail: "reset the file picker filter query",
  },
  {
    id: "picker-rows",
    category: "File Picker",
    combos: ["up", "down", "ctrl+p", "ctrl+n"],
    label: "Move selection",
    detail: "move through visible files and folders",
  },
  {
    id: "picker-tree",
    category: "File Picker",
    combos: ["left", "right"],
    label: "Collapse or expand",
    detail: "navigate the directory tree structure",
  },
  {
    id: "picker-pages",
    category: "File Picker",
    combos: ["pageup", "pagedown", "home", "end"],
    label: "Jump in list",
    detail: "move faster through long file lists",
  },
  {
    id: "picker-confirm",
    category: "File Picker",
    combos: ["enter"],
    label: "Confirm selection",
    detail: "insert the selected file into the draft",
  },
  {
    id: "terminal-suspend",
    category: "Terminal",
    keybind: "terminal_suspend",
    label: "Suspend terminal",
    detail: "suspend the current terminal process",
  },
]
