// Auto-generated by scripts/generate-tool-prompt-assets.ts
// Do not edit by hand.

import ActorAssign_Tool_brief_xnl from "./ActorAssign/Tool.brief.xnl" with { type: "text" }
import ActorAssign_Tool_detail_xnl from "./ActorAssign/Tool.detail.xnl" with { type: "text" }
import ActorStatus_Tool_brief_xnl from "./ActorStatus/Tool.brief.xnl" with { type: "text" }
import ActorStatus_Tool_detail_xnl from "./ActorStatus/Tool.detail.xnl" with { type: "text" }
import ActorUnwatch_Tool_brief_xnl from "./ActorUnwatch/Tool.brief.xnl" with { type: "text" }
import ActorUnwatch_Tool_detail_xnl from "./ActorUnwatch/Tool.detail.xnl" with { type: "text" }
import ActorWatch_Tool_brief_xnl from "./ActorWatch/Tool.brief.xnl" with { type: "text" }
import ActorWatch_Tool_detail_xnl from "./ActorWatch/Tool.detail.xnl" with { type: "text" }
import ApplyPatch_Tool_brief_xnl from "./ApplyPatch/Tool.brief.xnl" with { type: "text" }
import ApplyPatch_Tool_detail_xnl from "./ApplyPatch/Tool.detail.xnl" with { type: "text" }
import Bash_Tool_brief_xnl from "./Bash/Tool.brief.xnl" with { type: "text" }
import Bash_Tool_detail_xnl from "./Bash/Tool.detail.xnl" with { type: "text" }
import Batch_Tool_brief_xnl from "./Batch/Tool.brief.xnl" with { type: "text" }
import Batch_Tool_detail_xnl from "./Batch/Tool.detail.xnl" with { type: "text" }
import CoordinationStatus_Tool_brief_xnl from "./CoordinationStatus/Tool.brief.xnl" with { type: "text" }
import CoordinationStatus_Tool_detail_xnl from "./CoordinationStatus/Tool.detail.xnl" with { type: "text" }
import DetachedActorList_Tool_brief_xnl from "./DetachedActorList/Tool.brief.xnl" with { type: "text" }
import DetachedActorList_Tool_detail_xnl from "./DetachedActorList/Tool.detail.xnl" with { type: "text" }
import DetachedActorStatus_Tool_brief_xnl from "./DetachedActorStatus/Tool.brief.xnl" with { type: "text" }
import DetachedActorStatus_Tool_detail_xnl from "./DetachedActorStatus/Tool.detail.xnl" with { type: "text" }
import DetachedToolCall_Tool_brief_xnl from "./DetachedToolCall/Tool.brief.xnl" with { type: "text" }
import DetachedToolCall_Tool_detail_xnl from "./DetachedToolCall/Tool.detail.xnl" with { type: "text" }
import Edit_Tool_brief_xnl from "./Edit/Tool.brief.xnl" with { type: "text" }
import Edit_Tool_detail_xnl from "./Edit/Tool.detail.xnl" with { type: "text" }
import get_weather_Tool_brief_xnl from "./get_weather/Tool.brief.xnl" with { type: "text" }
import get_weather_Tool_detail_xnl from "./get_weather/Tool.detail.xnl" with { type: "text" }
import Glob_Tool_brief_xnl from "./Glob/Tool.brief.xnl" with { type: "text" }
import Glob_Tool_detail_xnl from "./Glob/Tool.detail.xnl" with { type: "text" }
import Grep_Tool_brief_xnl from "./Grep/Tool.brief.xnl" with { type: "text" }
import Grep_Tool_detail_xnl from "./Grep/Tool.detail.xnl" with { type: "text" }
import list_city_major_atractions_Tool_brief_xnl from "./list_city_major_atractions/Tool.brief.xnl" with { type: "text" }
import list_city_major_atractions_Tool_detail_xnl from "./list_city_major_atractions/Tool.detail.xnl" with { type: "text" }
import Ls_Tool_brief_xnl from "./Ls/Tool.brief.xnl" with { type: "text" }
import Ls_Tool_detail_xnl from "./Ls/Tool.detail.xnl" with { type: "text" }
import MemberAssign_Tool_brief_xnl from "./MemberAssign/Tool.brief.xnl" with { type: "text" }
import MemberAssign_Tool_detail_xnl from "./MemberAssign/Tool.detail.xnl" with { type: "text" }
import MemberCreate_Tool_brief_xnl from "./MemberCreate/Tool.brief.xnl" with { type: "text" }
import MemberCreate_Tool_detail_xnl from "./MemberCreate/Tool.detail.xnl" with { type: "text" }
import MemberList_Tool_brief_xnl from "./MemberList/Tool.brief.xnl" with { type: "text" }
import MemberList_Tool_detail_xnl from "./MemberList/Tool.detail.xnl" with { type: "text" }
import MemberStatus_Tool_brief_xnl from "./MemberStatus/Tool.brief.xnl" with { type: "text" }
import MemberStatus_Tool_detail_xnl from "./MemberStatus/Tool.detail.xnl" with { type: "text" }
import Multiedit_Tool_brief_xnl from "./Multiedit/Tool.brief.xnl" with { type: "text" }
import Multiedit_Tool_detail_xnl from "./Multiedit/Tool.detail.xnl" with { type: "text" }
import PlanReview_Tool_brief_xnl from "./PlanReview/Tool.brief.xnl" with { type: "text" }
import PlanReview_Tool_detail_xnl from "./PlanReview/Tool.detail.xnl" with { type: "text" }
import Questionnaire_Tool_brief_xnl from "./Questionnaire/Tool.brief.xnl" with { type: "text" }
import Questionnaire_Tool_detail_xnl from "./Questionnaire/Tool.detail.xnl" with { type: "text" }
import Read_Tool_brief_xnl from "./Read/Tool.brief.xnl" with { type: "text" }
import Read_Tool_detail_xnl from "./Read/Tool.detail.xnl" with { type: "text" }
import RunDelegateActor_Tool_brief_xnl from "./RunDelegateActor/Tool.brief.xnl" with { type: "text" }
import RunDelegateActor_Tool_detail_xnl from "./RunDelegateActor/Tool.detail.xnl" with { type: "text" }
import RunDetachedBash_Tool_brief_xnl from "./RunDetachedBash/Tool.brief.xnl" with { type: "text" }
import RunDetachedBash_Tool_detail_xnl from "./RunDetachedBash/Tool.detail.xnl" with { type: "text" }
import ShutdownRequest_Tool_brief_xnl from "./ShutdownRequest/Tool.brief.xnl" with { type: "text" }
import ShutdownRequest_Tool_detail_xnl from "./ShutdownRequest/Tool.detail.xnl" with { type: "text" }
import ShutdownStatus_Tool_brief_xnl from "./ShutdownStatus/Tool.brief.xnl" with { type: "text" }
import ShutdownStatus_Tool_detail_xnl from "./ShutdownStatus/Tool.detail.xnl" with { type: "text" }
import Skill_Tool_brief_xnl from "./Skill/Tool.brief.xnl" with { type: "text" }
import Skill_Tool_detail_xnl from "./Skill/Tool.detail.xnl" with { type: "text" }
import TaskTreeRead_Tool_brief_xnl from "./TaskTreeRead/Tool.brief.xnl" with { type: "text" }
import TaskTreeRead_Tool_detail_xnl from "./TaskTreeRead/Tool.detail.xnl" with { type: "text" }
import TaskTreeRead_Tool_flat_brief_xnl from "./TaskTreeRead/Tool.flat.brief.xnl" with { type: "text" }
import TaskTreeRead_Tool_flat_detail_xnl from "./TaskTreeRead/Tool.flat.detail.xnl" with { type: "text" }
import TaskTreeWrite_Tool_brief_xnl from "./TaskTreeWrite/Tool.brief.xnl" with { type: "text" }
import TaskTreeWrite_Tool_detail_xnl from "./TaskTreeWrite/Tool.detail.xnl" with { type: "text" }
import TaskTreeWrite_Tool_flat_brief_xnl from "./TaskTreeWrite/Tool.flat.brief.xnl" with { type: "text" }
import TaskTreeWrite_Tool_flat_detail_xnl from "./TaskTreeWrite/Tool.flat.detail.xnl" with { type: "text" }
import webfetch_Tool_brief_xnl from "./webfetch/Tool.brief.xnl" with { type: "text" }
import webfetch_Tool_detail_xnl from "./webfetch/Tool.detail.xnl" with { type: "text" }
import websearch_Tool_brief_xnl from "./websearch/Tool.brief.xnl" with { type: "text" }
import websearch_Tool_detail_xnl from "./websearch/Tool.detail.xnl" with { type: "text" }
import Write_Tool_brief_xnl from "./Write/Tool.brief.xnl" with { type: "text" }
import Write_Tool_detail_xnl from "./Write/Tool.detail.xnl" with { type: "text" }

export const toolPromptAssets = {
  "ActorAssign": {
    "Tool.brief.xnl": ActorAssign_Tool_brief_xnl,
    "Tool.detail.xnl": ActorAssign_Tool_detail_xnl,
  },
  "ActorStatus": {
    "Tool.brief.xnl": ActorStatus_Tool_brief_xnl,
    "Tool.detail.xnl": ActorStatus_Tool_detail_xnl,
  },
  "ActorUnwatch": {
    "Tool.brief.xnl": ActorUnwatch_Tool_brief_xnl,
    "Tool.detail.xnl": ActorUnwatch_Tool_detail_xnl,
  },
  "ActorWatch": {
    "Tool.brief.xnl": ActorWatch_Tool_brief_xnl,
    "Tool.detail.xnl": ActorWatch_Tool_detail_xnl,
  },
  "ApplyPatch": {
    "Tool.brief.xnl": ApplyPatch_Tool_brief_xnl,
    "Tool.detail.xnl": ApplyPatch_Tool_detail_xnl,
  },
  "Bash": {
    "Tool.brief.xnl": Bash_Tool_brief_xnl,
    "Tool.detail.xnl": Bash_Tool_detail_xnl,
  },
  "Batch": {
    "Tool.brief.xnl": Batch_Tool_brief_xnl,
    "Tool.detail.xnl": Batch_Tool_detail_xnl,
  },
  "CoordinationStatus": {
    "Tool.brief.xnl": CoordinationStatus_Tool_brief_xnl,
    "Tool.detail.xnl": CoordinationStatus_Tool_detail_xnl,
  },
  "DetachedActorList": {
    "Tool.brief.xnl": DetachedActorList_Tool_brief_xnl,
    "Tool.detail.xnl": DetachedActorList_Tool_detail_xnl,
  },
  "DetachedActorStatus": {
    "Tool.brief.xnl": DetachedActorStatus_Tool_brief_xnl,
    "Tool.detail.xnl": DetachedActorStatus_Tool_detail_xnl,
  },
  "DetachedToolCall": {
    "Tool.brief.xnl": DetachedToolCall_Tool_brief_xnl,
    "Tool.detail.xnl": DetachedToolCall_Tool_detail_xnl,
  },
  "Edit": {
    "Tool.brief.xnl": Edit_Tool_brief_xnl,
    "Tool.detail.xnl": Edit_Tool_detail_xnl,
  },
  "get_weather": {
    "Tool.brief.xnl": get_weather_Tool_brief_xnl,
    "Tool.detail.xnl": get_weather_Tool_detail_xnl,
  },
  "Glob": {
    "Tool.brief.xnl": Glob_Tool_brief_xnl,
    "Tool.detail.xnl": Glob_Tool_detail_xnl,
  },
  "Grep": {
    "Tool.brief.xnl": Grep_Tool_brief_xnl,
    "Tool.detail.xnl": Grep_Tool_detail_xnl,
  },
  "list_city_major_atractions": {
    "Tool.brief.xnl": list_city_major_atractions_Tool_brief_xnl,
    "Tool.detail.xnl": list_city_major_atractions_Tool_detail_xnl,
  },
  "Ls": {
    "Tool.brief.xnl": Ls_Tool_brief_xnl,
    "Tool.detail.xnl": Ls_Tool_detail_xnl,
  },
  "MemberAssign": {
    "Tool.brief.xnl": MemberAssign_Tool_brief_xnl,
    "Tool.detail.xnl": MemberAssign_Tool_detail_xnl,
  },
  "MemberCreate": {
    "Tool.brief.xnl": MemberCreate_Tool_brief_xnl,
    "Tool.detail.xnl": MemberCreate_Tool_detail_xnl,
  },
  "MemberList": {
    "Tool.brief.xnl": MemberList_Tool_brief_xnl,
    "Tool.detail.xnl": MemberList_Tool_detail_xnl,
  },
  "MemberStatus": {
    "Tool.brief.xnl": MemberStatus_Tool_brief_xnl,
    "Tool.detail.xnl": MemberStatus_Tool_detail_xnl,
  },
  "Multiedit": {
    "Tool.brief.xnl": Multiedit_Tool_brief_xnl,
    "Tool.detail.xnl": Multiedit_Tool_detail_xnl,
  },
  "PlanReview": {
    "Tool.brief.xnl": PlanReview_Tool_brief_xnl,
    "Tool.detail.xnl": PlanReview_Tool_detail_xnl,
  },
  "Questionnaire": {
    "Tool.brief.xnl": Questionnaire_Tool_brief_xnl,
    "Tool.detail.xnl": Questionnaire_Tool_detail_xnl,
  },
  "Read": {
    "Tool.brief.xnl": Read_Tool_brief_xnl,
    "Tool.detail.xnl": Read_Tool_detail_xnl,
  },
  "RunDelegateActor": {
    "Tool.brief.xnl": RunDelegateActor_Tool_brief_xnl,
    "Tool.detail.xnl": RunDelegateActor_Tool_detail_xnl,
  },
  "RunDetachedBash": {
    "Tool.brief.xnl": RunDetachedBash_Tool_brief_xnl,
    "Tool.detail.xnl": RunDetachedBash_Tool_detail_xnl,
  },
  "ShutdownRequest": {
    "Tool.brief.xnl": ShutdownRequest_Tool_brief_xnl,
    "Tool.detail.xnl": ShutdownRequest_Tool_detail_xnl,
  },
  "ShutdownStatus": {
    "Tool.brief.xnl": ShutdownStatus_Tool_brief_xnl,
    "Tool.detail.xnl": ShutdownStatus_Tool_detail_xnl,
  },
  "Skill": {
    "Tool.brief.xnl": Skill_Tool_brief_xnl,
    "Tool.detail.xnl": Skill_Tool_detail_xnl,
  },
  "TaskTreeRead": {
    "Tool.brief.xnl": TaskTreeRead_Tool_brief_xnl,
    "Tool.detail.xnl": TaskTreeRead_Tool_detail_xnl,
    "Tool.flat.brief.xnl": TaskTreeRead_Tool_flat_brief_xnl,
    "Tool.flat.detail.xnl": TaskTreeRead_Tool_flat_detail_xnl,
  },
  "TaskTreeWrite": {
    "Tool.brief.xnl": TaskTreeWrite_Tool_brief_xnl,
    "Tool.detail.xnl": TaskTreeWrite_Tool_detail_xnl,
    "Tool.flat.brief.xnl": TaskTreeWrite_Tool_flat_brief_xnl,
    "Tool.flat.detail.xnl": TaskTreeWrite_Tool_flat_detail_xnl,
  },
  "webfetch": {
    "Tool.brief.xnl": webfetch_Tool_brief_xnl,
    "Tool.detail.xnl": webfetch_Tool_detail_xnl,
  },
  "websearch": {
    "Tool.brief.xnl": websearch_Tool_brief_xnl,
    "Tool.detail.xnl": websearch_Tool_detail_xnl,
  },
  "Write": {
    "Tool.brief.xnl": Write_Tool_brief_xnl,
    "Tool.detail.xnl": Write_Tool_detail_xnl,
  },
} as const satisfies Record<string, Record<string, string>>

const toolPromptAssetMap: Record<string, Record<string, string>> = toolPromptAssets

export function getBundledToolPrompt(toolName: string, fileName: string): string | undefined {
  return toolPromptAssetMap[toolName]?.[fileName]
}
