import { readdirSync } from "fs"
import path from "path"

const repoRoot = path.resolve(import.meta.dir, "..")
const toolsRoot = path.join(repoRoot, "cell", "packages", "ai-organ-logic", "src", "composer", "AIAgent", "tools")
const outputPath = path.join(toolsRoot, "PromptAssets.generated.ts")

type ToolPromptFile = {
  fileName: string
  importId: string
}

type ToolPromptEntry = {
  toolName: string
  files: ToolPromptFile[]
}

function makeImportId(toolName: string, fileName: string): string {
  return `${toolName}_${fileName.replace(/[^a-zA-Z0-9]+/g, "_")}`.replace(/_+/g, "_")
}

const toolEntries: ToolPromptEntry[] = readdirSync(toolsRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => {
    const toolName = entry.name
    const toolDir = path.join(toolsRoot, toolName)
    const files = readdirSync(toolDir, { withFileTypes: true })
      .filter((file) => file.isFile() && file.name.endsWith(".xnl"))
      .map((file) => ({
        fileName: file.name,
        importId: makeImportId(toolName, file.name),
      }))
      .sort((left, right) => left.fileName.localeCompare(right.fileName))

    return {
      toolName,
      files,
    }
  })
  .filter((entry) => entry.files.length > 0)
  .sort((left, right) => left.toolName.localeCompare(right.toolName))

const lines: string[] = [
  "// Auto-generated by scripts/generate-tool-prompt-assets.ts",
  "// Do not edit by hand.",
  "",
]

for (const entry of toolEntries) {
  for (const file of entry.files) {
    lines.push(`import ${file.importId} from "./${entry.toolName}/${file.fileName}" with { type: "text" }`)
  }
}

lines.push("")
lines.push("export const toolPromptAssets = {")

for (const entry of toolEntries) {
  lines.push(`  ${JSON.stringify(entry.toolName)}: {`)
  for (const file of entry.files) {
    lines.push(`    ${JSON.stringify(file.fileName)}: ${file.importId},`)
  }
  lines.push("  },")
}

lines.push("} as const satisfies Record<string, Record<string, string>>")
lines.push("")
lines.push("const toolPromptAssetMap: Record<string, Record<string, string>> = toolPromptAssets")
lines.push("")
lines.push("export function getBundledToolPrompt(toolName: string, fileName: string): string | undefined {")
lines.push("  return toolPromptAssetMap[toolName]?.[fileName]")
lines.push("}")
lines.push("")

await Bun.write(outputPath, `${lines.join("\n")}`)
console.log(`Wrote ${path.relative(repoRoot, outputPath)}`)
