import { describe, expect, it } from "bun:test"
import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises"
import os from "node:os"
import path from "node:path"

import { loadResourceTree } from "halfcode-compiler.xnl/resource-core"

import {
  BUILTIN_EIDOLON_AGENT_REF,
  assertGeneratedArtifactCurrent,
  builtinEidolonResourceFiles,
  generateBuiltinEidolonVfsSnapshot,
  listBuiltinResourceFiles,
} from "../tools/generate-builtin-eidolon-vfs"

const packageRoot = path.resolve(import.meta.dir, "..")
const resourceRoot = path.join(packageRoot, "resources", "builtin-eidolon", ".eidolon", "resources")
const snapshotPath = path.join(packageRoot, "src", "builtin-vfs", "GeneratedBuiltinEidolonVfsSnapshot.xnl")

describe("Builtin mature Coding Agent resources", () => {
  it("owns one complete Halfcode package with a transport-neutral semantic identity", async () => {
    const tree = await loadResourceTree({ rootDir: resourceRoot })
    const records = [...tree.registry.byKind.values()].flat()
    const ids = records.map((record) => record.resourceId)

    expect(BUILTIN_EIDOLON_AGENT_REF).toBe("resource://eidolon.coding.CodeAgent")
    expect(ids).toContain("eidolon.coding.CodeAgent")
    expect(ids).toContain("eidolon.coding.KernelPrompt")
    expect(ids).toContain("eidolon.coding.CodingPrompt")
    expect(ids).toContain("eidolon.coding.WorkspaceAgents")
    expect(ids).toContain("eidolon.coding.StandardContext")
    expect(ids).toEqual(expect.arrayContaining(["bash", "edit", "glob", "grep", "ls", "read", "write"]))
    expect(ids.some((id) => id.includes("builtin"))).toBe(false)
    expect(tree.contentIdentities.size).toBe(records.length)
    expect(tree.contentIdentities.has("eidolon.coding.CodeAgent")).toBe(true)
  })

  it("keeps the mature ordered prefix and explicit context pipeline in the formal Agent", () => {
    const agent = builtinEidolonResourceFiles()["Agents/CodeAgent.xnl"]!
    expect(agent.indexOf("#kernel")).toBeLessThan(agent.indexOf("#coding"))
    expect(agent.indexOf("#coding")).toBeLessThan(agent.indexOf("#workspace"))
    expect(agent).toContain('ref = "resource://eidolon.coding.StandardContext"')
    expect(agent).toContain('ref = "resource://bash"')
    expect(agent).not.toContain("local.codument.proposition")
  })

  it("ships editable native Context and MessageSource code inside the managed resource package", () => {
    const files = builtinEidolonResourceFiles()
    expect(files["ContextPipelines/StandardContext.xnl"]).toContain("specVersion=2")
    expect(files["ContextPipelines/StandardContext.xnl"]).toContain('module = "./Code/standard-context.ts"')
    expect(files["MessageSources/WorkspaceAgents.xnl"]).toContain('module = "./Code/workspace-agents.ts"')
    expect(files["Code/standard-context.ts"]).toContain("runtime.materialize")
    expect(files["Code/workspace-agents.ts"]).toContain("runtime.readWorkspaceInstructions")
    expect(files["ContextPipelines/StandardContext.xnl"]).not.toContain('"implementation"')
  })

  it("commits the exact deterministic full VFS snapshot", async () => {
    const generated = generateBuiltinEidolonVfsSnapshot()
    expect(await readFile(snapshotPath, "utf8")).toBe(generated)
    expect(generateBuiltinEidolonVfsSnapshot()).toBe(generated)
    expect(generated).toContain("<VfsSnapshot")
    expect(generated).toContain("<Contents")
    expect(generated).toContain("eidolon_file_")
    expect(generated).toContain("eidolon_directory_")
  })

  it("binds node identity to logical path instead of mutable content", () => {
    const files = builtinEidolonResourceFiles()
    const baseline = generateBuiltinEidolonVfsSnapshot(files)
    const changed = generateBuiltinEidolonVfsSnapshot({
      ...files,
      "Prompts/CodingPrompt.xnl": `${files["Prompts/CodingPrompt.xnl"]}\n`,
    })
    const nodeIds = (source: string) => [...source.matchAll(/eidolon_(?:file|directory)_[a-f0-9]{24}/g)]
      .map((match) => match[0])
      .sort()
    expect(changed).not.toBe(baseline)
    expect(nodeIds(changed)).toEqual(nodeIds(baseline))
  })

  it("rejects unsafe resource coordinates and stale generated bytes", () => {
    expect(() => generateBuiltinEidolonVfsSnapshot({ "../escape.xnl": "<Escape>" }))
      .toThrow("Unsafe Builtin resource path")
    expect(() => generateBuiltinEidolonVfsSnapshot({ "nested//escape.xnl": "<Escape>" }))
      .toThrow("Unsafe Builtin resource path")
    expect(() => assertGeneratedArtifactCurrent("stale", "current", "snapshot.xnl"))
      .toThrow("artifact is stale")
  })

  it("rejects symlinked authoring entries", async () => {
    const root = await mkdtemp(path.join(os.tmpdir(), "eidolon-builtin-vfs-symlink-"))
    try {
      await mkdir(path.join(root, "Prompts"), { recursive: true })
      await writeFile(path.join(root, "outside.xnl"), "<Prompt>", "utf8")
      await symlink(path.join(root, "outside.xnl"), path.join(root, "Prompts", "Linked.xnl"))
      await expect(listBuiltinResourceFiles(path.join(root, "Prompts")))
        .rejects.toThrow("symlink is not supported")
    } finally {
      await rm(root, { recursive: true, force: true })
    }
  })
})
